@startuml

title Edit Rhythm Pattern

->PatternEditView: update()
loop for num in numSteps
    PatternEditView -> "stepButtons : ButtonGroup": buttonPressedNow(num)
    "stepButtons : ButtonGroup" --> PatternEditView: true
    PatternEditView -> PatternEditController: toggleStep(num)
    PatternEditController -> RhythmPatternManager: toggleActivePatternStep(num)
end

@enduml
